### ISSUE TITLE
帰りが遅い時通達する機能を付けたい

### ISSUE THREAD

**Issue by forno** [CIR-KIT/Raspberry-Pi-Studio-Daemon#5]
10時になってもOpen状態だったら帰れ(迫真)
ってなる機能を付ける。

**Comment by RyodoTanaka** [comment]
www
ええなそれ

**Comment by forno** [comment]
c++ の chrono さんは時間を管理できるけど日付とかはできないらしいので、
system_clock::to_time_t でtime_tに変換してctimeでいろいろこねくるのがよさ気
