### ISSUE TITLE
Raspberry pi 3のOSをRaspbianからUbuntu 16.04 or 17.10にしたい

### ISSUE THREAD

**Issue by forno** [CIR-KIT/Raspberry-Pi-Studio-Daemon#6]
現在動かしているのは @yamacir-kit が二年くらいのときにRaspbian入れたやつ。
いろいろとつらいのでUbuntuを入れたい。Unity Desktopはいらない子。

Ubuntu serverが入るならそちらでもよき。むしろそちらのほうがよき

**Comment by yamacir-kit** [comment]
ubuntu は一度しか試してない
結論としては（恐らく）黙って Raspbian を入れておくのがトータルで楽

その場合 C++14 辺りがギリギリ使えたはず
ただし、ARM プロセッサ向けの`libc++`には`thread`ライブラリにバグがあったはず

**Comment by yasu80** [comment]
MATE版にて安定動作しています．3のオンボードwifiも起動しています．

https://tiryoh.com/blog/archives/1101

の方法で ubuntu-mate-16.04-desktop-armhf-raspberry-pi-no-gui-ros-preinstalled20170129.img.xz イメージをRaspi 3 上で走らせたものを運用しています．ついでにROSも稼働します．．．

**Comment by yasu80** [comment]
Ubuntu Server のラズパイ向けビルドは起動時にラズパイのシステムが一瞬ロードされてから，おそらくはスタートアップ処理が実行されてからUbuntuが呼ばれてるように見えますが，これに信頼性がなくよく呼び出し不能になったりクラッシュしたりするのであまりおすすめしません．
