### ISSUE TITLE
一瞬だけ証明を付けた/消したときの動作を規定する。

### ISSUE THREAD

**Issue by forno** [CIR-KIT/Raspberry-Pi-Studio-Daemon#7]
現在、一瞬だけつけた/消したときは、その後に落ち着いた方の状態を報告する。

これにより、close -> 一瞬電気つける -> すぐしめる -> closeという報告が行われる。

これはこれでちょっとだけ操作したということがわかってよい動作なのですが、
close -> close という動作がわかりづらいという見方もあります。

一瞬だけつけられて、すぐに閉じられたという報告に変えることもできますし、
まあこのままでも良いという見方もできます。

どんな動作がいいかご意見募集中。

**Comment by Kose-i** [comment]
auto prev_data{Studio_daemon::open};
で、前回のデータを保有することにしました。
[branch]ko_test
